### ISSUE TITLE
a link within a page for each year in the top of the publication page?

### ISSUE THREAD

**Issue by sw005320** [shinjiwlab/shinjiwlab.github.io#39]
The publication page is too long...

**Comment by ftshijt** [comment]
I agree. I was thinking about that, but it seems a bit tricky to achieve the function from the template. I will seek some ways to do that

**Comment by ftshijt** [comment]
Oh! That could be an option. Internal links are working. But I was thinking about adding filters to the page directly (so that we could also filter publications with their categories and conferences).

**Comment by sw005320** [comment]
I see, but I think the internal links would be easier.
I like your filter idea, which can also filter the publications by topic or venue as a query.
If it is easy, we can do it, but otherwise, we may not have to do it.
